[workspace]
resolver = "3"
members = [ "adder", "advanced_traits","aggregator", "closures", "hello-async", "iterators", "lifetimes", "message_passing", "minigrep", "mutexes", "oop", "patterns", "smart_pointers", "threads", "traits", "unsafe_rust"]
