[workspace]
resolver = "3"
members = [ "adder","aggregator", "closures", "hello-async", "iterators", "lifetimes", "message_passing", "minigrep", "mutexes", "oop", "smart_pointers", "threads", "traits"]
